//          * this is a study helper for SDL2, generated by Knightu.

//*                                 1. Data Types:
#include <cstdint>

typedef struct Color
{
    uint8_t r;
    uint8_t g;
    uint8_t b;
    uint8_t a;
} Color;

typedef struct Pixel
{   //coordinators of a pixel
    float x;
    float y;
} Pixel;

typedef struct Segment
{

    Pixel xy1;      //starting pixel
    Pixel xy2;      // ending pixel
    Color color;
} Line;

typedef struct Coords   // only for the polygon
{
    float *x;
    float *y;
} Coords;

typedef struct Polygon
{
    Coords     coords;      //for the animation
    Color      color;       
    Pixel      center;      //the center of the form
    uint16_t   count;       //the count of the coordinates number
    float      length;      //the radius needed for animating . this means that it's the length needed for rendering
    float      real_length; //the length from the center and the most distant coordinate
    float      orientation; //the offset defining the incline of a form
} Polygon;

//things that are of type //*Polygon
typedef Polygon Arc;
typedef Polygon Hexagram;
typedef Polygon Pentagram;
typedef Polygon Star;
typedef Polygon Spiral;

//and all of them are //* Forms
typedef Polygon     Form;
typedef Arc         Form;
typedef Hexagram    Form;
typedef Pentagram   Form;
typedef Spiral      Form;
typedef Star        Form;

//? note: use everything as a form so you don't need to cast later.




